üêætrain_main
    EPOCHS: 15
    BATCH_SIZE: 512
    kifu_dir: backup/data_Q50000
    size: 9
    use_gpu: True
    rl: False
    window_size: 300000
    network_name: DualNet
    npz_dir: data
    ddp: True
    rl_num: -1
    rl_datetime: 
    input_opt: 
[20241030_141503] gen_sl_data start
    BATCH_SIZE: 512
    DATA_SET_SIZE: 1024000
    kifu_num: 0
üêætrain_on_gpu_ddp 2024-10-30 14:15:03.758589
    [20241030_141503] device
    torch.cuda.current_device:  0
    torch.cuda.device_count:  4
    torch.cuda.get_device_name(0):  GeForce RTX 2080 Ti
    torch.cuda.get_device_name(0):  GeForce RTX 2080 Ti
    torch.cuda.get_device_name(1):  GeForce RTX 2080 Ti
    torch.cuda.get_device_name(2):  GeForce RTX 2080 Ti
    torch.cuda.get_device_name(3):  GeForce RTX 2080 Ti
    torch.cuda.get_device_capability(0):  (7, 5)
    torch.cuda.get_device_capability(1):  (7, 5)
    torch.cuda.get_device_capability(1):  (7, 5)
    torch.cuda.get_device_capability(1):  (7, 5)
    torch.cuda.get_device_capability(2):  (7, 5)
    torch.cuda.get_device_capability(1):  (7, 5)
    torch.cuda.get_device_capability(3):  (7, 5)
    torch.cuda.get_device_capability(1):  (7, 5)
    torch.cuda.get_arch_list():  ['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80', 'sm_86']
Training data set : []
Testing data set  : []
[20241030_141503] monitoring
cpu: 50.6% [22.2, 22.2, 70.0, 30.0, 70.0, 90.0, 80.0, 20.0] üî•üî•
mem: 7.7% 
GeForce RTX 2080 Ti, 0, 0 %, 9 MiB, 4.72 W 
GeForce RTX 2080 Ti, 1, 0 %, 9 MiB, 21.76 W 
GeForce RTX 2080 Ti, 2, 0 %, 9 MiB, 21.74 W 
GeForce RTX 2080 Ti, 3, 0 %, 9 MiB, 22.14 W 
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [::ffff:127.0.0.1]:50000 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [::ffff:127.0.0.1]:50000 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:426] [c10d] The server socket cannot be initialized on [::]:50000 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [::ffff:127.0.0.1]:50000 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [::ffff:127.0.0.1]:50000 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [::ffff:127.0.0.1]:50000 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [::ffff:127.0.0.1]:50000 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [::ffff:127.0.0.1]:50000 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [::ffff:127.0.0.1]:50000 (errno: 97 - Address family not supported by protocol).
üêædevice:  0
[E ProcessGroupGloo.cpp:137] Rank 1 successfully reached monitoredBarrier, but received errors while waiting for send/recv from rank 0. Please check rank 0 logs for faulty rank.
[E ProcessGroupGloo.cpp:137] Rank 2 successfully reached monitoredBarrier, but received errors while waiting for send/recv from rank 0. Please check rank 0 logs for faulty rank.
üêædevice:  1
üêædevice:  2
[E ProcessGroupGloo.cpp:137] Rank 3 successfully reached monitoredBarrier, but received errors while waiting for send/recv from rank 0. Please check rank 0 logs for faulty rank.
üêædevice:  3
Traceback (most recent call last):
  File "train.py", line 116, in <module>
    train_main() # pylint: disable=E1120
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "train.py", line 107, in train_main
    train_on_gpu_ddp(program_dir=program_dir,board_size=size,  batch_size=BATCH_SIZE, epochs=EPOCHS, network_name=network_name, npz_dir=npz_dir)
  File "/data/student/u2424004/igo/TantamaGo/nn/learn.py", line 614, in train_on_gpu_ddp
    torch.multiprocessing.spawn(train_on_gpu_ddp_worker, args=(torch.cuda.device_count(), train_data_set, test_data_set, program_dir, board_size, BATCH_SIZE, EPOCHS, network_name, npz_dir), nprocs = torch.cuda.device_count(), join = True)
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/data/student/u2424004/igo/TantamaGo/nn/learn.py", line 560, in train_on_gpu_ddp_worker
    print_evaluation_information(test_loss, epoch, test_iteration, testing_time)
  File "/data/student/u2424004/igo/TantamaGo/nn/utility.py", line 78, in print_evaluation_information
    loss, policy_loss, value_loss = _calculate_losses(loss_data, iteration)
  File "/data/student/u2424004/igo/TantamaGo/nn/utility.py", line 43, in _calculate_losses
    return loss["loss"] / iteration, loss["policy"] / iteration, \
ZeroDivisionError: float division by zero

